ALTER TABLE "SchoolPhoto"
  ADD COLUMN "focalX" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "focalY" INTEGER NOT NULL DEFAULT 50;

ALTER TABLE "Post"
  ADD COLUMN "coverFocalX" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "coverFocalY" INTEGER NOT NULL DEFAULT 50;
